name: CI

on: [push, pull_request]

jobs:
  test-units:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Run test units
        run: |
          cargo test --release --all-features --workspace
